[package]
name = "word_trie"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
jemallocator = "0.5"

[profile.release]
debug = true # needed for flamegraphs etc.

